### PR TITLE
Add experimental support for Rust dependencies with Cargo

### LINKED ISSUE #252: Support Cargo
This'd be nice to have for Rust projects, and the packages have defined licenses, e.g. https://crates.io/crates/libc

### PR DESCRIPTION
**Pull request by ChrisMacNaughton**
Closes #252

### CODE REVIEW

**Comment by xtreme-lisheng-tai** [comment]
Hey @ChrisMacNaughton , 
Is there any particular reason you changed the Dockerfile from `Ubuntu:trusty` to `ruby:2.5.1`? 
We aim to support multiple version of ruby. 

Also i believe you will need to rebase on master in order to resolve some of the issues currently seen within CI. 

Let us know if you have any questions

**Comment by ChrisMacNaughton** [comment]
I updated the Dockerfile simply to reduce the build time, given that the Dockerfile only installs Ruby 2.5.1 anyways, will remove that change and rebase on Master

**Comment by ChrisMacNaughton** [comment]
I see that, since my change, the RVM install has been updated to support multiple versions of Ruby, whereas it only did the single version when I made this PR

**Comment by xtreme-lisheng-tai** [comment]
Awesome! Thanks for the Pull-request @ChrisMacNaughton!

**Comment by xtreme-shane-lattanzio** [comment]
Bumping for webhook trigger.

**Pull request merged**
