### PR TITLE
Add support for PHP via Composer

### PR DESCRIPTION
**Pull request by SimantovYousoufov**
Added a `composer` and `composer_package` handlers as well as specs+fixtures for both and a travis config.

I tried to keep with the existing code style but as this is my first dive into the Ruby world so please let me know of any conventions I didn't follow and I'll resolve them ASAP. Would be much appreciated :).

Please note that I added `sudo: required` to `.travis.yml` to get TravisCI to build correctly. There were no whitelisted repositories from which I could use the `apt` option to install PHP. This approach should probably be revisited.

### CODE REVIEW

**Comment by flavorjones** [comment]
Thanks for submitting this! I'll find some time to deeply read the commits later this week, but I'm totally on board with adding Composer support!

**Comment by SimantovYousoufov** [comment]
@flavorjones: Any feedback? :)

**Comment by flavorjones** [comment]
Apologies for the delay, I've been quite busy lately. Will try hard to take a look in the next couple of days.

**Comment by lbayerl** [comment]
I'd love to see composer being supported!

**Comment by pivotal-issuemaster** [comment]
@SimantovYousoufov Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=231)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=231) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@SimantovYousoufov Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=231)!

**Comment by hkdobrev** [comment]
Any updates on this? Thanks!

**Comment by kdykeman** [comment]
There's been a good number of changes since this PR was submitted. There was some refactoring around the package managers, and there was also a switch over to Concourse for CI. I believe it hadn't been merged because it was failing under Travis back when it was submitted. I think it needs to be rebased and re-aligned to fit with the current codebase.

**Comment by kdykeman** [comment]
Closing this for now as the PR has languished. Future efforts will be tracked in association with #518

**Pull request closed without merging**
