### PR TITLE
Initial Checkin of Obvious Fix to add CC license.

### PR DESCRIPTION
**Pull request by ff-spierce**
Obvious Fix

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ff-spierce Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=478)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=478) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ff-spierce This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by xtreme-shane-lattanzio** [comment]
@ff-spierce Thanks for the PR! One minor thing. It looks like you included the license finder gem as a part of your commit. This is not necessary as we build the gem through our CI with your updated code once merged. When you get a chance, please remove this and rebase and it should make CI happy.

**Comment by ff-spierce** [comment]
Rebased and removed the gem.  Thx.

**Pull request merged**
