### PR TITLE
Adds `spdx` field for licenses

### PR DESCRIPTION
**Pull request by petems**
* Initial work to get spdx matching for licenses

I want to see if I'm on the right track for this

Related https://github.com/pivotal/LicenseFinder/issues/218

### CODE REVIEW

**Comment by kdykeman** [comment]
Thanks @petems. From what I'm seeing so far it looks to be on the right track. I'll get another set of eyes to look the PR over within the next week.

I'm not sure if you were already thinking this as well, but it would probably also be friendlier to downstream tools if the reports could optionally list licenses using their spdx names.  That could be a separate PR.

**Comment by Manifaust** [comment]
@petems thanks for the PR, we have a couple questions.

You implemented `spdx` as an array, but aren't spdx entries unique, that is, there is a single name/id for each license in the [official list of spdx licenses](https://spdx.org/licenses/)?

Second, since there are so many licenses in that list, is it a good idea to introduce a new hardcoded property in the list of licenses in `Definitions`? I'm not sure yet what is the best way to go forward. But @flavorjones mentioned in the tagged issue the gem [spdx-licenses](https://github.com/domcleal/spdx-licenses). Maybe instead of introducing a new field, we can create a function that delegates to that gem? What do you think?

**Comment by petems** [comment]
@Manifaust The gem is just for checking that a license given is actually a valid SPDX code, you can't use it for detecting. So I think we stilll need the field.

But it's a good idea to add it in for validation, so I did! 😄 

@kdykeman Can I get some more eyes on this PR? 😄

**Comment by xtreme-lisheng-tai** [comment]
closing, since this has been opened for quite awhile.

**Pull request closed without merging**
